name: Feature request
description: I want new feature that it not exist currently
title: "[Feature]: "
labels: ["Type: enhancement"]
assignees:
  - kamontat
body:
  - type: markdown
    attributes:
      value: |
        Please look into currently issue created to not duplicate the request
  - type: textarea
    id: what-happened
    attributes:
      label: |
        Describe the solution you'd like?
      description: |
        Briefly detail what do you want?
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: |
        Additional context?
      description: |
        Anything else I need to aware of?
    validations:
      required: false
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: What module you refer to?
      options:
        - ftgenerator
        - fthelper
    validations:
      required: true
