FROM busybox:1.33.1

WORKDIR /fth
# copy compiled script
COPY ftgenerator /fth
# copy config and environment file
COPY generator /fth

ENTRYPOINT [ \
  "/fth/ftgenerator", \
  "--pwd", "/fth", \
  "--envs", "/fth/.env.docker"]
