version: "3"

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
        --logfile "/freqtrade/user_data/logs/freqtrade.log"
        --config "/freqtrade/user_data/config.json"
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config-rest-.json version | grep -q version"]
      interval: 30s
      timeout: 4s
      retries: 3
      start_period: 1m
  # single mode
  ftmetric:
    image: ghcr.io/kamontat/ftmetric:v5.0.0-beta.12
    container_name: ftmetric
    restart: on-failure
    environment:
      - FTH_INTERNAL__LOG__LEVEL=3 # enabled info log

      - FTH_FREQTRADE__HTTP__ENABLED=true
      - FTH_FREQTRADE__HTTP__URL=http://freqtrade:8080
      - FTH_FREQTRADE__HTTP__USERNAME=freqtrade
      - FTH_FREQTRADE__HTTP__PASSWORD=password

      - FTH_FREQTRADE__DB__ENABLED=true
      - FTH_FREQTRADE__DB__TYPE=postgres
      - FTH_FREQTRADE__DB__URL=postgres:5432
      - FTH_FREQTRADE__DB__USERNAME=freqtrade
      - FTH_FREQTRADE__DB__NAME=database_name
      - FTH_FREQTRADE__DB__PASSWORD=password

      - FTH_SERVER__PORT=8090
    depends_on:
      - freqtrade
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/healthcheck"]
      interval: 20s
      timeout: 1s
      retries: 3
      start_period: 20s
  # cluster mode
  ftmetricct:
    image: ghcr.io/kamontat/ftmetric:v5.0.0-beta.12
    container_name: ftmetricct
    restart: on-failure
    environment:
      - FTH_INTERNAL__LOG__LEVEL=3 # enabled info log
      - FTH_CLUSTERS=1A,2A

      - FTC_1A__FREQTRADE__HTTP__ENABLED=true
      - FTC_1A__FREQTRADE__HTTP__URL=http://freqtrade:8080
      - FTC_1A__FREQTRADE__HTTP__USERNAME=freqtrade
      - FTC_1A__FREQTRADE__HTTP__PASSWORD=password
      - FTC_1A__FREQTRADE__DB__ENABLED=false
      - FTC_1A__FREQTRADE__DB__TYPE=postgres
      - FTC_1A__FREQTRADE__DB__URL="localhost:5432"
      - FTC_1A__FREQTRADE__DB__NAME="freqtrade"
      - FTC_1A__FREQTRADE__DB__USERNAME="freqtrade"
      - FTC_1A__FREQTRADE__DB__PASSWORD="password"

      - FTC_2A__FREQTRADE__HTTP__ENABLED=true
      - FTC_2A__FREQTRADE__HTTP__URL="http://localhost:8081"
      - FTC_2A__FREQTRADE__HTTP__USERNAME="freqtrade"
      - FTC_2A__FREQTRADE__HTTP__PASSWORD="password"
      - FTC_2A__FREQTRADE__DB__ENABLED=false

      - FTH_SERVER__PORT=8090
