name: Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # https://crontab.guru/#0_5_*_*_1

jobs:
  changelog:
    name: "Changelog"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install git-chglog
        run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      - name: Version
        run: |
          git-chglog --version
          gh --version
      - name: Generate changelog
        run: git-chglog --output CHANGELOG.md
      - name: Setup git
        run: |
          git config --global user.name 'kamontat [bot]'
          git config --global user.email 'developer@kamontat.net'
      - name: Commit and push change
        run: |
          branch_name="release/$(date +'%y%m%d')"

          git checkout -b "$branch_name"
          git commit -am "chore: auto generate changelog [skip ci]"
          git push --set-upstream origin "$branch_name"
      - name: Create Pull request
        run: |
          gh auth status
          gh pr create --title "chore: release note ($(date +'%y%m%d'))" --label "Type: Release" --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
