name: StaleBot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_3_*_*_1

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue is closed because it has been stale. Please create another issue if it persist'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This PR is closed because it has been stale. Please create another PR if you still working on it'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'Status: Stale'
          close-issue-label: 'Trigger: Close'
          exempt-issue-labels: 'Status: Whitelist,Status: NEW'
          stale-pr-label: 'Status: Stale'
          close-pr-label: 'Trigger: Close'
          exempt-pr-labels: 'Status: Whitelist,Status: NEW'
